package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i   the first index to swap
     * @param j   the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * 
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int j = 0; j < arr.length - 1; j++) {
            for (int i = 0; i < arr.length - 1 - j; i++) {
                events.add(new CompareEvent<>(i, i + 1));
                if (arr[i].compareTo(arr[i + 1]) > 0) {
                    swap(arr, i, i + 1);
                    events.add(new SwapEvent<>(i, i + 1));
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * 
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();

        for (int i = 0; i < arr.length; i++) {
            int min = i;
            for (int j = i + 1; j < arr.length; j++) {
                events.add(new CompareEvent<>(min, j));
                if (arr[min].compareTo(arr[j]) > 0) {
                    min = j;
                }
            }
            swap(arr, min, i);
            events.add(new SwapEvent<>(min, i));
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * 
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 1; i < arr.length; i++) {
            for (int j = i; j > 0; j--) {
                events.add(new CompareEvent<>(j, j - 1));
                if (arr[j].compareTo(arr[j - 1]) > 0) {
                    break;
                } else {
                    swap(arr, j, j - 1);
                    events.add(new SwapEvent<>(j, j - 1));
                }
            }
        }
        return events;
    }

    /**
     * Divides the subarray into two halves, recursively sorts each half, and then merges them 
     * back into a temporary array
     * 
     * @param arr    the array being sorted
     * @param copy   a temporary array for merging
     * @param start  the starting index of the subarray to merge
     * @param end    the ending index of the subarray to merge
     * @param events the list of sort events
     */
    public static <T extends Comparable<? super T>> void mergeHelper(T[] arr, T[] copy, int start,
            int end, List<SortEvent<T>> events) {
        if (start == end - 1) {
            return;
        }

        int mid = start + (end - start) / 2;

        mergeHelper(arr, copy, start, mid, events);
        mergeHelper(arr, copy, mid, end, events);

        int i = start;
        int j = mid;
        int k = start;

        while (i < mid && j < end) {
            events.add(new CompareEvent<>(i, j));
            if ((arr[i]).compareTo((T) arr[j]) < 0) {
                copy[k] = arr[i];
                k++;
                i++;
            } else {
                copy[k] = arr[j];
                k++;
                j++;
            }
        }

        while (i < mid) {
            copy[k] = arr[i];
            k++;
            i++;
        }
        while (j < end) {
            copy[k] = arr[j];
            k++;
            j++;
        }

        for (int m = start; m < end; m++) {
            arr[m] = copy[m];
            events.add(new CopyEvent<>(m, copy[m]));
        }
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     *
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        T[] copy = Arrays.copyOf(arr, arr.length);
        mergeHelper(arr, copy, 0, arr.length, events);
        return events;
    }

    /**
     * Returns the index where the median of the three elements
     * 
     * @param low the index of the lower bound
     * @param high the index of the upper bound
     * @param arr the array being sorted
     * @param events the list of sort events
     * @return the index where the median of the three elements
     */
    private static <T extends Comparable<? super T>> int medianOfThree(T[] arr, int low, int high,
            List<SortEvent<T>> events) {
        int mid = low + (high - low) / 2;

        // Move the median to index mid
        events.add(new CompareEvent<>(low, mid));
        if (arr[low].compareTo(arr[mid]) > 0) {
            swap(arr, low, mid);
            events.add(new SwapEvent<>(low, mid));
        }

        events.add(new CompareEvent<>(low, high));
        if (arr[low].compareTo(arr[high]) > 0) {
            swap(arr, low, high);
            events.add(new SwapEvent<>(low, high));

        }

        events.add(new CompareEvent<>(mid, high));
        if (arr[mid].compareTo(arr[high]) > 0) {
            swap(arr, mid, high);
            events.add(new SwapEvent<>(mid, high));

        }
        return mid;
    }

    /**
     * Returns the pivot value
     * @param low the lowest index
     * @param high the highest index
     * @param arr the array to sort
     * @param events the list of sort events
     * @return the pivot
     */
    private static <T extends Comparable<? super T>> int pivotGetter(T[] arr, int low, int high,
            List<SortEvent<T>> events) {
        int pivotIndex = medianOfThree(arr, low, high, events);
        T pivot = arr[pivotIndex];

        // Move pivot to end
        swap(arr, pivotIndex, high);
        events.add(new SwapEvent<>(pivotIndex, high));

        int i = low - 1;

        for (int j = low; j < high; j++) {
            events.add(new CompareEvent<>(j, pivotIndex));
            if (arr[j].compareTo(pivot) <= 0) {
                i++;
                swap(arr, i, j);
                events.add(new SwapEvent<>(i, j));
            }
        }

        // Place pivot in correct position
        swap(arr, i + 1, high);
        events.add(new SwapEvent<>(i + 1, high));
        return i + 1;
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param events the list of sort events
     * @return the sort events generated by this sort
     */
    private static <T extends Comparable<? super T>> void quickSortHelper(T[] arr, int low, int high,
            List<SortEvent<T>> events) {
        if (low < high) {
            int pivotIndex = pivotGetter(arr, low, high, events);
            quickSortHelper(arr, low, pivotIndex - 1, events); // Sort left half
            quickSortHelper(arr, pivotIndex + 1, high, events); // Sort right half
        }
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        quickSortHelper(arr, 0, arr.length - 1, events);
        return events;
    }

    /**
     * Helper method
     * 
     * @param <T>    the carrier type of the array
     * @param arr    the array representing the heap
     * @param n      the size of the heap
     * @param i      the index of the current root
     * @param events the list of sort events
     */
    public static <T extends Comparable<? super T>> void heapify(T[] arr, int size, int i, List<SortEvent<T>> events) {
        // on the first iteration i is always 0
        int max = i;
        int left = 2 * i + 1;
        int right = 2 * i + 2;

        if (left < size) {
            events.add(new CompareEvent<>(left, max));
            if (arr[left].compareTo(arr[max]) > 0) {
                max = left;
            }
        }

        if (right < size) {
            events.add(new CompareEvent<>(right, max));
            if (arr[right].compareTo(arr[max]) > 0) {
                max = right;
            }
        }

        if (max != i) {
            swap(arr, i, max);
            events.add(new SwapEvent<>(i, max));
            heapify(arr, size, max, events);
        }

    }

    /**
     * Sorts the array according to the heap sort algorithm
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> heapSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        // build max heap
        // arr.length/2 - 1 = 2 is the last parent
        for (int i = arr.length / 2 - 1; i >= 0; i--) {
            heapify(arr, arr.length, i, events);
        }

        // Extract elements from the heap
        for (int i = arr.length - 1; i > 0; i--) {
            // Move the root (largest element) to the end
            swap(arr, 0, i);
            events.add(new SwapEvent<>(0, i));

            // Rebuild the heap with the reduced array
            heapify(arr, i, 0, events);
        }
        return events;
    }

    /**
     * Applies events to the list in-order.
     * @param l an array of Ts
     * @param events list of SortEvent<T> objectts.
     */
    public static <T> void eventSort(T[] l, List<SortEvent<T>> events) {
        for (int i = 0; i < events.size(); i++) {
            events.get(i).apply(l);
        }
    }
}
